### ISSUE TITLE
Add HTML code with there screenshots

### ISSUE THREAD

**Issue by idivyanshbansal** [idivyanshbansal/hacktoberfest#3]

**Comment by ManishS6** [comment]
@idivyanshbansal I would like to work on this
Please assign this task to me.

**Comment by ManishS6** [comment]
also please tell me what would you like the HTML page to have.

**Comment by idivyanshbansal** [comment]
Go for it @ManishS6

**Comment by ManishS6** [comment]
> Go for it @ManishS6

Please assign me the task. Also what would you like the HTML page to have.

**Comment by idivyanshbansal** [comment]
You can make a folder in which you will put all the requirements and assets for that HTML. 
The HTML page can be any animation, 404-page, design, portfolio, contact form, landing page, etc.

**Comment by ManishS6** [comment]
@idivyanshbansal on it thanks.

**Comment by ManishS6** [comment]
@idivyanshbansal I have completed the task in  PR #5
